### ISSUE TITLE
Won't Scan

### ISSUE THREAD

**Issue by Jab2870** [xenomachina/dvdrip#1]
Hi,

I am trying to use this but am getting stuck.

When running `dvdrip --scan /dev/sr0` I get a problem

```
dvdrip: error: unrecognized arguments: /dev/sr0
```

If I add the `-i` flag, I get slightly further:

```
Reading from '/mnt/cd'
Disc claims to have 14 titles.
```

But I get stuck there.

Any ideas?

**Comment by xenomachina** [comment]
> If I add the -i flag, I get slightly further:
> 
> ```
> Reading from '/mnt/cd'
> Disc claims to have 14 titles.
> ```
>
> But I get stuck there.

It's possible that the disc has copy protection. Some DVDs have a title that throw rippers into a loop. When backing up some of my discs I've had luck with specifying an individual title on the command-line. You can also try opening it in Handbrake's GUI to see what happens. If Handbrake can't rip it, then this script can't rip it, as it's really just a controller to automate Handbrake.

You're right that you need to use the `-i` option to specify the input. Did you see some docs somewhere that showed an example without the `-i` option?

**Comment by Jab2870** [comment]
The readme doesn't have the `-i` option, nor does the `--help` text.

Thanks.

Unfortunately, i am running this over ssh on a headless server.  The GUI version of handbrake isn't an option.

If anyone else runs into this problem, I managed to get some information using `HandBrakeCLI --scan --title 0 -i /mnt/cd`. Part of the output was this:

```
+ title 11:
  + Main Feature
  + vts 8, ttn 1, cells 0->30 (3125591 blocks)
  + duration: 02:03:30
  + size: 720x576, pixel aspect: 64/45, display aspect: 1.78, 25.000 fps
  + autocrop: 12/12/10/8
  + support opencl: no
  + chapters:
    + 1: cells 0->0, 88098 blocks, duration 00:03:08
    + 2: cells 1->1, 114733 blocks, duration 00:05:30
    + 3: cells 2->2, 137140 blocks, duration 00:04:50
    + 4: cells 3->3, 36451 blocks, duration 00:01:22
    + 5: cells 4->4, 72561 blocks, duration 00:03:00
    + 6: cells 5->5, 40236 blocks, duration 00:01:47
    + 7: cells 6->6, 56990 blocks, duration 00:02:32
    + 8: cells 7->7, 100332 blocks, duration 00:04:25
    + 9: cells 8->8, 52767 blocks, duration 00:01:57
    + 10: cells 9->9, 72034 blocks, duration 00:02:40
    + 11: cells 10->10, 59405 blocks, duration 00:02:31
    + 12: cells 11->11, 183643 blocks, duration 00:07:27
    + 13: cells 12->12, 96011 blocks, duration 00:04:18
    + 14: cells 13->13, 109589 blocks, duration 00:04:37
    + 15: cells 14->15, 122221 blocks, duration 00:05:11
    + 16: cells 16->16, 67105 blocks, duration 00:02:55
    + 17: cells 17->18, 131061 blocks, duration 00:05:10
    + 18: cells 19->19, 277156 blocks, duration 00:09:40
    + 19: cells 20->20, 49378 blocks, duration 00:02:09
    + 20: cells 21->21, 265493 blocks, duration 00:10:21
    + 21: cells 22->22, 95084 blocks, duration 00:03:39
    + 22: cells 23->23, 53662 blocks, duration 00:02:16
    + 23: cells 24->24, 163407 blocks, duration 00:06:27
    + 24: cells 25->25, 187759 blocks, duration 00:06:42
    + 25: cells 26->26, 53073 blocks, duration 00:01:57
    + 26: cells 27->27, 194847 blocks, duration 00:06:34
    + 27: cells 28->28, 102001 blocks, duration 00:03:33
    + 28: cells 29->29, 143175 blocks, duration 00:06:54
    + 29: cells 30->30, 179 blocks, duration 00:00:00
  + audio tracks:
    + 1, English (AC3) (5.1 ch) (iso639-2: eng), 48000Hz, 448000bps
    + 2, English (DTS) (5.1 ch) (iso639-2: eng), 48000Hz, 768000bps
  + subtitle tracks:
    + 1, English (Closed Caption) (iso639-2: eng) (Bitmap)(VOBSUB)
```

Now, running `dvdrip --scan -i /dev/sr0 -t 11` seems to be working.

Thanks for your help and for developing this

**Comment by xenomachina** [comment]
Thanks for the update! It looks like I did indeed miss correcting some examples in the README and --help. (The `-i` used to not be required.)
