### ISSUE TITLE
error: unrecognized arguments: /dev/cdrom

### ISSUE THREAD

**Issue by Cassiopeia23** [xenomachina/dvdrip#6]
Or did I just executed it wrong ?

python3 dvdrip.py --scan /dev/cdrom usage: dvdrip.py [-h] [-v] [-c] [-n] [--scan] [--main-feature] [-t TITLES]
                 [-i INPUT] [-o OUTPUT] [--mount-timeout MOUNT_TIMEOUT]
dvdrip.py: error: unrecognized arguments: /dev/cdrom

**Comment by xenomachina** [comment]
Try adding `-i` before `/dev/cdrom`
